/**
 * Unit tests for lib/stellar/validation.ts (Stellar address validation).
 */
import { describe, it, expect } from 'vitest';
import { Keypair, StrKey } from '@stellar/stellar-sdk';

import {
  isValidStellarAddress,
  isValidSecretKey,
  isValidMuxedAddress,
  isValidContractId,
  isValidAnyStellarAddress,
  getAddressType,
} from '../lib/stellar/validation';

// Valid, real keys generated by the SDK (deterministic at runtime).
const publicKey = Keypair.random().publicKey();
const secretKey = Keypair.random().secret();
const muxedAddress = StrKey.encodeMed25519PublicKey(
  Buffer.concat([Buffer.alloc(32), Buffer.from([0, 0, 0, 0, 0, 0, 0, 42])])
);
const contractId = StrKey.encodeContract(Buffer.alloc(32));

describe('isValidStellarAddress', () => {
  it('accepts a valid public key', () => {
    expect(isValidStellarAddress(publicKey)).toBe(true);
  });

  it('rejects malformed inputs', () => {
    expect(isValidStellarAddress('')).toBe(false);
    expect(isValidStellarAddress('not-an-address')).toBe(false);
    expect(isValidStellarAddress('A' + publicKey.slice(1))).toBe(false); // wrong prefix
    expect(isValidStellarAddress(publicKey.slice(0, 55))).toBe(false); // wrong length
    expect(isValidStellarAddress(publicKey.slice(0, 55) + 'A')).toBe(false); // bad checksum
  });
});

describe('isValidSecretKey', () => {
  it('accepts a valid secret key', () => {
    expect(isValidSecretKey(secretKey)).toBe(true);
  });

  it('rejects malformed inputs', () => {
    expect(isValidSecretKey('')).toBe(false);
    expect(isValidSecretKey('S' + 'A'.repeat(55))).toBe(false);
    expect(isValidSecretKey(publicKey)).toBe(false);
  });
});

describe('isValidMuxedAddress', () => {
  it('accepts a valid muxed address', () => {
    expect(isValidMuxedAddress(muxedAddress)).toBe(true);
  });

  it('rejects non-muxed addresses', () => {
    expect(isValidMuxedAddress(publicKey)).toBe(false);
    expect(isValidMuxedAddress('M' + 'A'.repeat(68))).toBe(false);
  });
});

describe('isValidContractId', () => {
  it('accepts a valid contract id', () => {
    expect(isValidContractId(contractId)).toBe(true);
  });

  it('rejects non-contract ids', () => {
    expect(isValidContractId(publicKey)).toBe(false);
    expect(isValidContractId('C' + 'A'.repeat(55))).toBe(false);
  });
});

describe('isValidAnyStellarAddress', () => {
  it('accepts public, muxed, and contract addresses', () => {
    expect(isValidAnyStellarAddress(publicKey)).toBe(true);
    expect(isValidAnyStellarAddress(muxedAddress)).toBe(true);
    expect(isValidAnyStellarAddress(contractId)).toBe(true);
  });

  it('rejects garbage', () => {
    expect(isValidAnyStellarAddress('garbage')).toBe(false);
  });
});

describe('getAddressType', () => {
  it('classifies each address kind', () => {
    expect(getAddressType(publicKey)).toBe('public');
    expect(getAddressType(muxedAddress)).toBe('muxed');
    expect(getAddressType(contractId)).toBe('contract');
    expect(getAddressType('nope')).toBe('invalid');
  });
});
